version: '3'

services:
  postgres:
    image: postgis/postgis:15-master
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES=MusicLibraryService

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

    # http://localhost:9444/ui
  s3-ninja:
    image: scireum/s3-ninja
    container_name: s3-ninja-
    ports:
      - '9444:9000'
    user: '2000:2000'
